// Codegen: inline every per-tenant migration .sql file into a TypeScript
// module so the SQL can be applied from inside a bundled Next.js app
// (server actions), where runtime fs reads of files outside the bundle
// are unreliable.
//
// The CLI runner (per-tenant-migrate.ts) and the in-app provisioning path
// (per-tenant-provision.ts → provisionTenantFull) both consume the
// generated PER_TENANT_MIGRATIONS array, so there is a single source of
// truth for the ordered migration list.
//
//   Run after adding/editing any migrations/per-tenant/*.sql file:
//     pnpm -F @tracey/db db:generate-per-tenant-sql
//
// The generated file is committed (it is an artifact, not a build-time
// step) so deploys never depend on the codegen running.

import path from "node:path";
import fs from "node:fs/promises";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR = path.resolve(here, "..", "..", "migrations", "per-tenant");
const OUT_FILE = path.resolve(here, "..", "per-tenant-migrations.generated.ts");

async function main() {
  const files = (await fs.readdir(MIGRATIONS_DIR))
    .filter((f) => f.endsWith(".sql"))
    .sort();

  const entries: string[] = [];
  for (const file of files) {
    const sql = await fs.readFile(path.join(MIGRATIONS_DIR, file), "utf8");
    const name = file.replace(/\.sql$/, "");
    // JSON.stringify gives a correctly-escaped double-quoted JS string
    // literal (handles quotes, backslashes, newlines, $$ dollar-quotes).
    entries.push(`  { name: ${JSON.stringify(name)}, sql: ${JSON.stringify(sql)} },`);
  }

  const banner = `// AUTO-GENERATED by src/cli/generate-per-tenant-sql.ts — DO NOT EDIT BY HAND.
// Regenerate with: pnpm -F @tracey/db db:generate-per-tenant-sql
// Source: packages/db/migrations/per-tenant/*.sql (${files.length} files)
`;

  const body = `${banner}
export interface PerTenantMigration {
  readonly name: string;
  readonly sql: string;
}

/** Ordered per-tenant migrations, inlined from disk at codegen time. */
export const PER_TENANT_MIGRATIONS: readonly PerTenantMigration[] = [
${entries.join("\n")}
];
`;

  await fs.writeFile(OUT_FILE, body, "utf8");
  console.log(
    `[generate-per-tenant-sql] wrote ${files.length} migrations → ${path.relative(process.cwd(), OUT_FILE)}`,
  );
}

main().catch((err) => {
  console.error("[generate-per-tenant-sql] failed:", err);
  process.exit(1);
});
