CREATE SCHEMA "app";
--> statement-breakpoint
CREATE TABLE "app"."ai_studio_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"tenant_id" uuid NOT NULL,
	"history" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"files" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"current_module_json" text,
	"module_id" integer,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."audit_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid,
	"actor_user_id" uuid,
	"actor_email" text,
	"action" text NOT NULL,
	"target_kind" text,
	"target_id" text,
	"details" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."invitations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"email" text NOT NULL,
	"role" text DEFAULT 'member' NOT NULL,
	"token" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"invited_by_user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "invitations_role_chk" CHECK ("app"."invitations"."role" in ('owner','admin','member'))
);
--> statement-breakpoint
CREATE TABLE "app"."members" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"role" text DEFAULT 'member' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "members_role_chk" CHECK ("app"."members"."role" in ('owner','admin','member'))
);
--> statement-breakpoint
CREATE TABLE "app"."notifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"recipient_user_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"title" text NOT NULL,
	"body" text,
	"action_url" text,
	"read_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."processed_stripe_events" (
	"event_id" text PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"processed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."tenants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_user_id" uuid NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"plan" text DEFAULT 'free' NOT NULL,
	"status" text DEFAULT 'trialing' NOT NULL,
	"trial_ends_at" timestamp with time zone DEFAULT now() + interval '14 days' NOT NULL,
	"current_period_end" timestamp with time zone,
	"cancel_at_period_end" boolean DEFAULT false NOT NULL,
	"canceled_at" timestamp with time zone,
	"stripe_customer_id" text,
	"stripe_subscription_id" text,
	"seats_purchased" integer DEFAULT 0 NOT NULL,
	"timezone" text DEFAULT 'Australia/Sydney' NOT NULL,
	"audit_mode" boolean DEFAULT false NOT NULL,
	"audit_mode_settings" jsonb DEFAULT '{"hideUnpublishedModules":true,"hideIncompleteAssignments":true,"hideFailedAttempts":true,"hideInactiveEmployees":true,"hideExpiredWhs":true,"hideAuditOnlyRoutes":true}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tenants_plan_chk" CHECK ("app"."tenants"."plan" in ('free','starter','pro','enterprise')),
	CONSTRAINT "tenants_status_chk" CHECK ("app"."tenants"."status" in ('trialing','active','past_due','canceled')),
	CONSTRAINT "tenants_timezone_chk" CHECK (length("app"."tenants"."timezone") > 0)
);
--> statement-breakpoint
CREATE TABLE "app"."users" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" text,
	"email" text NOT NULL,
	"image" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "assignments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assignments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"module_id" integer NOT NULL,
	"assigned_at" timestamp DEFAULT now(),
	"due_at" timestamp,
	"completed_at" timestamp,
	"version_id" integer,
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "attempts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"module_id" integer NOT NULL,
	"score" integer DEFAULT 0,
	"correct" integer DEFAULT 0,
	"total" integer DEFAULT 0,
	"passed" boolean DEFAULT false,
	"answers_json" text DEFAULT '{}',
	"created_at" timestamp DEFAULT now(),
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"user_id" integer,
	"actor_email" text DEFAULT '',
	"actor_name" text DEFAULT '',
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" integer,
	"summary" text DEFAULT '',
	"details_json" text DEFAULT '',
	"ip_address" text DEFAULT '',
	"user_agent" text DEFAULT '',
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "choices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "choices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"question_id" integer NOT NULL,
	"text" text NOT NULL,
	"is_correct" boolean DEFAULT false,
	"position" integer DEFAULT 0,
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "content_item_media" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "content_item_media_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"content_item_id" integer NOT NULL,
	"file_path" text NOT NULL,
	"kind" text DEFAULT '',
	"position" integer DEFAULT 0,
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "content_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "content_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"module_id" integer NOT NULL,
	"kind" text NOT NULL,
	"title" text NOT NULL,
	"body" text DEFAULT '',
	"file_path" text DEFAULT '',
	"position" integer DEFAULT 0,
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "department_module_policies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "department_module_policies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"department_id" integer NOT NULL,
	"module_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "departments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "departments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "employers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "employers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "machine_modules" (
	"machine_id" integer NOT NULL,
	"module_id" integer NOT NULL,
	"tracey_tenant_id" uuid NOT NULL,
	CONSTRAINT "machine_modules_machine_id_module_id_pk" PRIMARY KEY("machine_id","module_id")
);
--> statement-breakpoint
CREATE TABLE "machines" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "machines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"department_id" integer,
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "module_media" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "module_media_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"module_id" integer NOT NULL,
	"file_path" text NOT NULL,
	"kind" text DEFAULT '',
	"position" integer DEFAULT 0,
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "module_versions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "module_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"module_id" integer NOT NULL,
	"version_number" integer NOT NULL,
	"snapshot_json" text NOT NULL,
	"created_by_id" integer,
	"created_at" timestamp DEFAULT now(),
	"summary" text DEFAULT '',
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "modules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "modules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"description" text DEFAULT '',
	"created_at" timestamp DEFAULT now(),
	"is_published" boolean DEFAULT true,
	"created_by_id" integer,
	"cover_path" text DEFAULT '',
	"valid_for_days" integer,
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "positions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "positions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"parent_id" integer,
	"department_id" integer,
	"sort_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "questions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "questions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"module_id" integer NOT NULL,
	"prompt" text NOT NULL,
	"kind" text DEFAULT 'single',
	"position" integer DEFAULT 0,
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "uploaded_files" (
	"filename" text PRIMARY KEY NOT NULL,
	"mime_type" text DEFAULT 'application/octet-stream' NOT NULL,
	"data" "bytea" NOT NULL,
	"size" integer DEFAULT 0,
	"uploaded_by_id" integer,
	"uploaded_at" timestamp DEFAULT now(),
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_machines" (
	"user_id" integer NOT NULL,
	"machine_id" integer NOT NULL,
	"tracey_tenant_id" uuid NOT NULL,
	CONSTRAINT "user_machines_user_id_machine_id_pk" PRIMARY KEY("user_id","machine_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"name" text NOT NULL,
	"first_name" text DEFAULT '',
	"last_name" text DEFAULT '',
	"password_hash" text NOT NULL,
	"role" text DEFAULT 'employee' NOT NULL,
	"is_active_flag" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"phone" text DEFAULT '',
	"department_id" integer,
	"employer_id" integer,
	"start_date" date,
	"termination_date" date,
	"photo_filename" text,
	"job_title" text DEFAULT '',
	"manager_id" integer,
	"position_id" integer,
	"tracey_user_id" text,
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "whs_kinds" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "whs_kinds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"label" text NOT NULL,
	"category" text NOT NULL,
	"is_system" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "whs_records" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "whs_records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind" text NOT NULL,
	"user_id" integer,
	"title" text NOT NULL,
	"issued_on" date,
	"expires_on" date,
	"notes" text DEFAULT '',
	"document_filename" text,
	"last_reminded_at" timestamp,
	"incident_date" date,
	"severity" text,
	"reported_by_id" integer,
	"created_at" timestamp DEFAULT now(),
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sc_locations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tracey_tenant_id" uuid NOT NULL,
	"name" text NOT NULL,
	"timezone" text DEFAULT 'Australia/Sydney' NOT NULL,
	"address" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sc_locations_timezone_chk" CHECK (length("sc_locations"."timezone") > 0)
);
--> statement-breakpoint
CREATE TABLE "sc_shift_assignments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tracey_tenant_id" uuid NOT NULL,
	"shift_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"status" text DEFAULT 'offered' NOT NULL,
	"responded_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sc_assignments_status_chk" CHECK ("sc_shift_assignments"."status" in ('offered','accepted','declined','swapped','no_show'))
);
--> statement-breakpoint
CREATE TABLE "sc_shifts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tracey_tenant_id" uuid NOT NULL,
	"location_id" uuid NOT NULL,
	"role" text NOT NULL,
	"starts_at" timestamp with time zone NOT NULL,
	"ends_at" timestamp with time zone NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"notes" text,
	"created_by_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sc_shifts_status_chk" CHECK ("sc_shifts"."status" in ('draft','published','cancelled')),
	CONSTRAINT "sc_shifts_time_chk" CHECK ("sc_shifts"."ends_at" > "sc_shifts"."starts_at")
);
--> statement-breakpoint
CREATE TABLE "sc_time_off_requests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tracey_tenant_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"reason" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"reviewed_by_user_id" uuid,
	"reviewed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sc_time_off_status_chk" CHECK ("sc_time_off_requests"."status" in ('pending','approved','denied','cancelled')),
	CONSTRAINT "sc_time_off_dates_chk" CHECK ("sc_time_off_requests"."end_date" >= "sc_time_off_requests"."start_date")
);
--> statement-breakpoint
ALTER TABLE "app"."ai_studio_sessions" ADD CONSTRAINT "ai_studio_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."ai_studio_sessions" ADD CONSTRAINT "ai_studio_sessions_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."audit_events" ADD CONSTRAINT "audit_events_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "app"."tenants"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."audit_events" ADD CONSTRAINT "audit_events_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "app"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."invitations" ADD CONSTRAINT "invitations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."invitations" ADD CONSTRAINT "invitations_invited_by_user_id_users_id_fk" FOREIGN KEY ("invited_by_user_id") REFERENCES "app"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."members" ADD CONSTRAINT "members_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."members" ADD CONSTRAINT "members_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."notifications" ADD CONSTRAINT "notifications_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."notifications" ADD CONSTRAINT "notifications_recipient_user_id_users_id_fk" FOREIGN KEY ("recipient_user_id") REFERENCES "app"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."tenants" ADD CONSTRAINT "tenants_owner_user_id_users_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignments" ADD CONSTRAINT "assignments_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempts" ADD CONSTRAINT "attempts_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "choices" ADD CONSTRAINT "choices_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content_item_media" ADD CONSTRAINT "content_item_media_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content_items" ADD CONSTRAINT "content_items_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "department_module_policies" ADD CONSTRAINT "department_module_policies_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "departments" ADD CONSTRAINT "departments_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "employers" ADD CONSTRAINT "employers_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "machine_modules" ADD CONSTRAINT "machine_modules_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "machines" ADD CONSTRAINT "machines_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "module_media" ADD CONSTRAINT "module_media_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "module_versions" ADD CONSTRAINT "module_versions_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "modules" ADD CONSTRAINT "modules_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "positions" ADD CONSTRAINT "positions_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "questions" ADD CONSTRAINT "questions_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "uploaded_files" ADD CONSTRAINT "uploaded_files_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_machines" ADD CONSTRAINT "user_machines_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "whs_kinds" ADD CONSTRAINT "whs_kinds_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "whs_records" ADD CONSTRAINT "whs_records_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sc_locations" ADD CONSTRAINT "sc_locations_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sc_shift_assignments" ADD CONSTRAINT "sc_shift_assignments_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sc_shift_assignments" ADD CONSTRAINT "sc_shift_assignments_shift_id_sc_shifts_id_fk" FOREIGN KEY ("shift_id") REFERENCES "public"."sc_shifts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sc_shift_assignments" ADD CONSTRAINT "sc_shift_assignments_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sc_shifts" ADD CONSTRAINT "sc_shifts_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sc_shifts" ADD CONSTRAINT "sc_shifts_location_id_sc_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."sc_locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sc_shifts" ADD CONSTRAINT "sc_shifts_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "app"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sc_time_off_requests" ADD CONSTRAINT "sc_time_off_requests_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sc_time_off_requests" ADD CONSTRAINT "sc_time_off_requests_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sc_time_off_requests" ADD CONSTRAINT "sc_time_off_requests_reviewed_by_user_id_users_id_fk" FOREIGN KEY ("reviewed_by_user_id") REFERENCES "app"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "ai_studio_sessions_user_tenant_uq" ON "app"."ai_studio_sessions" USING btree ("user_id","tenant_id");--> statement-breakpoint
CREATE INDEX "audit_events_tenant_created_idx" ON "app"."audit_events" USING btree ("tenant_id","created_at");--> statement-breakpoint
CREATE INDEX "audit_events_action_idx" ON "app"."audit_events" USING btree ("action");--> statement-breakpoint
CREATE UNIQUE INDEX "invitations_token_uq" ON "app"."invitations" USING btree ("token");--> statement-breakpoint
CREATE UNIQUE INDEX "members_tenant_user_uq" ON "app"."members" USING btree ("tenant_id","user_id");--> statement-breakpoint
CREATE INDEX "notifications_recipient_created_idx" ON "app"."notifications" USING btree ("recipient_user_id","tenant_id","created_at");--> statement-breakpoint
CREATE INDEX "notifications_recipient_unread_idx" ON "app"."notifications" USING btree ("recipient_user_id","read_at");--> statement-breakpoint
CREATE UNIQUE INDEX "tenants_slug_uq" ON "app"."tenants" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "tenants_stripe_customer_id_uq" ON "app"."tenants" USING btree ("stripe_customer_id");--> statement-breakpoint
CREATE UNIQUE INDEX "tenants_stripe_subscription_id_uq" ON "app"."tenants" USING btree ("stripe_subscription_id");--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_uq" ON "app"."users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "sc_locations_tenant_idx" ON "sc_locations" USING btree ("tracey_tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX "sc_shift_user_uq" ON "sc_shift_assignments" USING btree ("shift_id","user_id");--> statement-breakpoint
CREATE INDEX "sc_assignments_tenant_idx" ON "sc_shift_assignments" USING btree ("tracey_tenant_id");--> statement-breakpoint
CREATE INDEX "sc_assignments_user_idx" ON "sc_shift_assignments" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sc_shifts_tenant_starts_idx" ON "sc_shifts" USING btree ("tracey_tenant_id","starts_at");--> statement-breakpoint
CREATE INDEX "sc_shifts_location_starts_idx" ON "sc_shifts" USING btree ("location_id","starts_at");--> statement-breakpoint
CREATE INDEX "sc_time_off_tenant_idx" ON "sc_time_off_requests" USING btree ("tracey_tenant_id","start_date");--> statement-breakpoint
CREATE INDEX "sc_time_off_user_idx" ON "sc_time_off_requests" USING btree ("user_id","start_date");