CREATE TABLE "position_module_policies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "position_module_policies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"position_id" integer NOT NULL,
	"module_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"tracey_tenant_id" uuid NOT NULL
);
--> statement-breakpoint
ALTER TABLE "position_module_policies" ADD CONSTRAINT "position_module_policies_tracey_tenant_id_tenants_id_fk" FOREIGN KEY ("tracey_tenant_id") REFERENCES "app"."tenants"("id") ON DELETE cascade ON UPDATE no action;